name: Platforms

on:
  workflow_call:
    outputs:
      matrix:
        description: 'Platforms from .github/platforms.yml as JSON, to be used as a job matrix'
        value: ${{ jobs.platforms.outputs.matrix }}

jobs:
  platforms:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - name: Checkout platforms file
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
          sparse-checkout: .github/platforms.yml
          sparse-checkout-cone-mode: false
      - id: set
        run: echo "matrix=$(yq -o=json -I=0 .github/platforms.yml)" >> "$GITHUB_OUTPUT"
