name: Platforms

on:
  workflow_call:
    outputs:
      matrix:
        description: 'JSON list of supported platforms ({ runs-on, platform }) to use as a job matrix'
        value: ${{ jobs.platforms.outputs.matrix }}

jobs:
  platforms:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        run: |
          matrix=$(jq -c . <<'EOF'
          [
            { "runs-on": "ubuntu-24.04-arm", "platform": "linux-arm64" },
            { "runs-on": "ubuntu-latest", "platform": "linux-x64" },
            { "runs-on": "macos-15-intel", "platform": "macos-x64" },
            { "runs-on": "macos-latest", "platform": "macos-arm64" },
            { "runs-on": "windows-latest", "platform": "windows-x64" }
          ]
          EOF
          )
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
